/*
-- Query: select * from comision
LIMIT 0, 1000

-- Date: 2017-09-26 00:12
*/
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (2,1,'RODRIGUEZ NIETO, Felipe Jorge',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (3,1,'RODRIGUEZ NIETO, Felipe Jorge',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (4,1,'MAISULS, Ivan',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (5,1,'MAISULS, Ivan',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (6,2,'RODRIGUEZ NIETO, Felipe Jorge',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (7,2,'RODRIGUEZ NIETO, Felipe Jorge',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (8,2,'MAISULS, Ivan',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (9,2,'MAISULS, Ivan',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (10,1,'EGUES, Nahuel Ernesto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (11,2,'AROCAS, Sergio Martín',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (12,3,'CLANCIG, Andrés Juan',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (13,4,'RODRIGUEZ, Maria Sol',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (14,5,'GOMEZ, Roberto Guillermo',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (15,6,'FERNANDEZ, Leonardo Daniel',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (16,7,'DIAZ, Hugo Alberto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (17,8,'DE RITO, Pablo Norberto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (18,9,'FERRELLI, Martín Miguiel',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (19,10,'EGUES, Nahuel Ernesto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (20,11,'CLANCIG, Andrés Juan',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (21,12,'ROMANI, Fabio Roque',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (22,13,'DIAZ, Hugo Alberto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (23,14,'PERDICARO, Sebastián Salvador',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (24,0,'PERDICARO, Sebastián Salvador',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (25,1,'SUAREZ SCHMITZ, Anibal',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (26,2,'VILA ROZA, Eleonora Julia',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (27,3,'A DESIGNAR',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (28,4,'A DESIGNAR',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (29,5,'ZUBIK, Daniel Roberto',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (30,6,'ZUBIK, Daniel Roberto',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (31,7,'SARAROLS, Valeria Graciela',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (32,8,'FIGARI BIZZOTTO, Sabina',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (33,9,'FIGARI BIZZOTTO, Sabina',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (34,10,'FRETES, Sonia Mabel',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (35,11,'MILANESIO, Fernando Oscar',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (36,12,'MILANESIO, Fernando Oscar',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (37,13,'PASSAROTTI, Ivana Marina',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (38,14,'PASSAROTTI, Ivana Marina',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (39,15,'A DESIGNAR',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (40,16,'ETCHEZAR, Carlos Mariano',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (41,17,'ETCHEZAR, Carlos Mariano',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (42,18,'PASSARO, Juan Antonio',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (43,19,'MARQUEZ POLANCO, Milagro',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (44,20,'MARQUEZ POLANCO, Milagro',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (45,21,'BREA, Barbara Celeste',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (46,1,'VILCHES ANTAO, Diego Gastón',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (47,2,'HARARI, Viviana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (48,3,'HARARI, Viviana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (49,4,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (50,5,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (51,6,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (52,7,'MICHALINA, Claudio Antonio',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (53,8,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (54,9,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (55,10,'HARARI, Ivana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (56,11,'HARARI, Ivana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (57,12,'ARIAS, Germán Carlos',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (58,13,'MICHALINA, Claudio Antonio',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (59,14,'A DESIGNAR',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (60,15,'PALACIOS, Eliseo',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (61,16,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (62,17,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (63,18,'A DESIGNAR',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (64,1,'VILCHES ANTAO, Diego Gastón',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (65,2,'HARARI, Viviana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (66,3,'HARARI, Viviana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (67,4,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (68,5,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (69,6,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (70,7,'MICHALINA, Claudio Antonio',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (71,8,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (72,9,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (73,10,'HARARI, Ivana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (74,11,'HARARI, Ivana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (75,12,'ARIAS, Germán Carlos',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (76,13,'MICHALINA, Claudio Antonio',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (77,14,'A DESIGNAR',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (78,15,'PALACIOS, Eliseo',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (79,16,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (80,17,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (81,18,'A DESIGNAR',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (82,1,'BRUNOVSKY, Vanesa',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (83,1,'BRUNOVSKY, Vanesa',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (84,2,'GUZZETTI, Alberto',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (85,3,'SOLASSI, Hector Edgardo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (86,3,'SOLASSI, Hector Edgardo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (87,4,'SOLASSI, Hector Edgardo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (88,4,'SOLASSI, Hector Edgardo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (89,5,'PINGARO, Gonzalo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (90,5,'PINGARO, Gonzalo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (91,6,'TAVARONE, María Florencia',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (92,6,'TAVARONE, María Florencia',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (93,7,'MADSEN, Juan José',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (94,7,'MADSEN, Juan José',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (95,8,'MADSEN, Juan José',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (96,8,'MADSEN, Juan José',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (97,9,'PINGARO, Gonzalo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (98,9,'PINGARO, Gonzalo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (99,10,'PODESTA, Melina Daniela',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (100,10,'PODESTA, Melina Daniela',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (101,11,'ABDEL MASIH, Samira',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (102,11,'ABDEL MASIH, Samira',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (103,12,'PIRIZ, Alejandro Victor',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (104,12,'PIRIZ, Alejandro Victor',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (105,13,'BAGU, Diego Rubén',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (106,13,'BAGU, Diego Rubén',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (107,14,'TAVARONE, María Florencia',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (108,14,'TAVARONE, María Florencia',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (109,15,'FIORE, Santiago',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (110,15,'FIORE, Santiago',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (111,0,'LABATTI, Oscar Leandro',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (112,0,'LABATTI, Oscar Leandro',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (113,1,'VAVELIUK, Pablo',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (114,1,'VAVELIUK, Pablo',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (115,2,'LUNA, Gerardo Juan Manuel',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (116,2,'LUNA, Gerardo Juan Manuel',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (117,3,'BIURRUN, Anahi',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (118,3,'BIURRUN, Anahi',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (119,4,'ALMIRON, Evangelina',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (120,4,'ALMIRON, Evangelina',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (121,5,'GAINLE, Fabio Germán',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (122,5,'GAINLE, Fabio Germán',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (123,6,'BIURRUN, Anahi',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (124,6,'BIURRUN, Anahi',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (125,7,'AGNELLI, Fernando Mario',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (126,7,'AGNELLI, Fernando Mario',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (127,1,'BAUM, Lorena',2,2017,66);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (128,1,'BAUM, Lorena',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (129,2,'BAUM, Lorena',2,2017,75);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (130,3,'ABDEL MASIH, Samira',2,2017,89);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (131,3,'ABDEL MASIH, Samira',2,2017,94);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (132,1,'DUARTE, Gabriel Alejandro',2,2017,75);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (133,1,'DUARTE, Gabriel Alejandro',2,2017,89);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (134,2,'DUARTE, Gabriel Alejandro',2,2017,94);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (135,1,'CAPPELLETTI, Marcelo Angel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (136,1,'CAPPELLETTI, Marcelo Angel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (137,2,'FRIZZERA, Victor Daniel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (138,2,'FRIZZERA, Victor Daniel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (139,3,'IRASTORZA, Ramiro Miguel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (140,3,'IRASTORZA, Ramiro Miguel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (141,4,'ALONSO, Roberto Emilio',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (142,4,'ALONSO, Roberto Emilio',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (143,5,'CABRA, DANIEL CARLOS',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (144,5,'CABRA, DANIEL CARLOS',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (145,1,'PASSARO, Juan Antonio',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (146,1,'PASSARO, Juan Antonio',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (147,2,'GUAREPI, Valentín',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (148,2,'GUAREPI, Valentín',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (149,3,'GUAREPI, Valentín',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (150,3,'GUAREPI, Valentín',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (151,4,'FERRARA, Carlos Gaston',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (152,4,'FERRARA, Carlos Gaston',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (153,1,'FERNANDEZ, Leandro Carlos',2,2017,89);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (154,2,'SCARAMUZZA, Carlos Jose',2,2017,89);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (155,1,'SCARAMUZZA, Carlos Jose',2,2017,95);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (156,2,'SCARAMUZZA, Carlos Jose',2,2017,95);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (157,1,'A DESIGNAR',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (158,2,'BALDINO, Emiliano',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (159,3,'BALDINO, Emiliano',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (160,4,'BALDINO, Emiliano',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (161,1,'DE RONDE, Chirstian',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (162,1,'RODRIGUEZ NIETO, Felipe Jorge',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (163,1,'RODRIGUEZ NIETO, Felipe Jorge',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (164,1,'MAISULS, Ivan',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (165,1,'MAISULS, Ivan',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (166,2,'RODRIGUEZ NIETO, Felipe Jorge',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (167,2,'RODRIGUEZ NIETO, Felipe Jorge',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (168,2,'MAISULS, Ivan',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (169,2,'MAISULS, Ivan',2,2017,77);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (170,1,'EGUES, Nahuel Ernesto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (171,2,'AROCAS, Sergio Martín',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (172,3,'CLANCIG, Andrés Juan',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (173,4,'RODRIGUEZ, Maria Sol',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (174,5,'GOMEZ, Roberto Guillermo',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (175,6,'FERNANDEZ, Leonardo Daniel',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (176,7,'DIAZ, Hugo Alberto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (177,8,'DE RITO, Pablo Norberto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (178,9,'FERRELLI, Martín Miguiel',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (179,10,'EGUES, Nahuel Ernesto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (180,11,'CLANCIG, Andrés Juan',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (181,12,'ROMANI, Fabio Roque',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (182,13,'DIAZ, Hugo Alberto',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (183,14,'PERDICARO, Sebastián Salvador',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (184,0,'PERDICARO, Sebastián Salvador',2,2017,53);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (185,1,'SUAREZ SCHMITZ, Anibal',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (186,2,'VILA ROZA, Eleonora Julia',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (187,3,'A DESIGNAR',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (188,4,'A DESIGNAR',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (189,5,'ZUBIK, Daniel Roberto',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (190,6,'ZUBIK, Daniel Roberto',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (191,7,'SARAROLS, Valeria Graciela',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (192,8,'FIGARI BIZZOTTO, Sabina',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (193,9,'FIGARI BIZZOTTO, Sabina',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (194,10,'FRETES, Sonia Mabel',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (195,11,'MILANESIO, Fernando Oscar',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (196,12,'MILANESIO, Fernando Oscar',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (197,13,'PASSAROTTI, Ivana Marina',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (198,14,'PASSAROTTI, Ivana Marina',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (199,15,'A DESIGNAR',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (200,16,'ETCHEZAR, Carlos Mariano',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (201,17,'ETCHEZAR, Carlos Mariano',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (202,18,'PASSARO, Juan Antonio',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (203,19,'MARQUEZ POLANCO, Milagro',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (204,20,'MARQUEZ POLANCO, Milagro',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (205,21,'BREA, Barbara Celeste',2,2017,55);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (206,1,'VILCHES ANTAO, Diego Gastón',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (207,2,'HARARI, Viviana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (208,3,'HARARI, Viviana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (209,4,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (210,5,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (211,6,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (212,7,'MICHALINA, Claudio Antonio',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (213,8,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (214,9,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (215,10,'HARARI, Ivana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (216,11,'HARARI, Ivana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (217,12,'ARIAS, Germán Carlos',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (218,13,'MICHALINA, Claudio Antonio',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (219,14,'A DESIGNAR',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (220,15,'PALACIOS, Eliseo',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (221,16,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (222,17,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (223,18,'A DESIGNAR',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (224,1,'VILCHES ANTAO, Diego Gastón',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (225,2,'HARARI, Viviana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (226,3,'HARARI, Viviana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (227,4,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (228,5,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (229,6,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (230,7,'MICHALINA, Claudio Antonio',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (231,8,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (232,9,'SEGOVIA AGUIRRE, Wenddy Vanessa',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (233,10,'HARARI, Ivana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (234,11,'HARARI, Ivana',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (235,12,'ARIAS, Germán Carlos',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (236,13,'MICHALINA, Claudio Antonio',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (237,14,'A DESIGNAR',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (238,15,'PALACIOS, Eliseo',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (239,16,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (240,17,'MORALES, Ceferino Alvaro',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (241,18,'A DESIGNAR',2,2017,59);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (242,1,'BRUNOVSKY, Vanesa',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (243,1,'BRUNOVSKY, Vanesa',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (244,2,'GUZZETTI, Alberto',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (245,3,'SOLASSI, Hector Edgardo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (246,3,'SOLASSI, Hector Edgardo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (247,4,'SOLASSI, Hector Edgardo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (248,4,'SOLASSI, Hector Edgardo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (249,5,'PINGARO, Gonzalo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (250,5,'PINGARO, Gonzalo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (251,6,'TAVARONE, María Florencia',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (252,6,'TAVARONE, María Florencia',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (253,7,'MADSEN, Juan José',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (254,7,'MADSEN, Juan José',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (255,8,'MADSEN, Juan José',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (256,8,'MADSEN, Juan José',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (257,9,'PINGARO, Gonzalo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (258,9,'PINGARO, Gonzalo',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (259,10,'PODESTA, Melina Daniela',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (260,10,'PODESTA, Melina Daniela',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (261,11,'ABDEL MASIH, Samira',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (262,11,'ABDEL MASIH, Samira',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (263,12,'PIRIZ, Alejandro Victor',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (264,12,'PIRIZ, Alejandro Victor',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (265,13,'BAGU, Diego Rubén',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (266,13,'BAGU, Diego Rubén',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (267,14,'TAVARONE, María Florencia',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (268,14,'TAVARONE, María Florencia',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (269,15,'FIORE, Santiago',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (270,15,'FIORE, Santiago',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (271,0,'LABATTI, Oscar Leandro',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (272,0,'LABATTI, Oscar Leandro',2,2017,60);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (273,1,'VAVELIUK, Pablo',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (274,1,'VAVELIUK, Pablo',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (275,2,'LUNA, Gerardo Juan Manuel',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (276,2,'LUNA, Gerardo Juan Manuel',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (277,3,'BIURRUN, Anahi',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (278,3,'BIURRUN, Anahi',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (279,4,'ALMIRON, Evangelina',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (280,4,'ALMIRON, Evangelina',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (281,5,'GAINLE, Fabio Germán',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (282,5,'GAINLE, Fabio Germán',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (283,6,'BIURRUN, Anahi',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (284,6,'BIURRUN, Anahi',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (285,7,'AGNELLI, Fernando Mario',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (286,7,'AGNELLI, Fernando Mario',2,2017,61);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (287,1,'BAUM, Lorena',2,2017,66);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (288,1,'BAUM, Lorena',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (289,2,'BAUM, Lorena',2,2017,75);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (290,3,'ABDEL MASIH, Samira',2,2017,89);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (291,3,'ABDEL MASIH, Samira',2,2017,94);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (292,1,'DUARTE, Gabriel Alejandro',2,2017,75);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (293,1,'DUARTE, Gabriel Alejandro',2,2017,89);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (294,2,'DUARTE, Gabriel Alejandro',2,2017,94);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (295,1,'CAPPELLETTI, Marcelo Angel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (296,1,'CAPPELLETTI, Marcelo Angel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (297,2,'FRIZZERA, Victor Daniel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (298,2,'FRIZZERA, Victor Daniel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (299,3,'IRASTORZA, Ramiro Miguel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (300,3,'IRASTORZA, Ramiro Miguel',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (301,4,'ALONSO, Roberto Emilio',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (302,4,'ALONSO, Roberto Emilio',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (303,5,'CABRA, DANIEL CARLOS',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (304,5,'CABRA, DANIEL CARLOS',2,2017,65);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (305,1,'PASSARO, Juan Antonio',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (306,1,'PASSARO, Juan Antonio',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (307,2,'GUAREPI, Valentín',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (308,2,'GUAREPI, Valentín',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (309,3,'GUAREPI, Valentín',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (310,3,'GUAREPI, Valentín',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (311,4,'FERRARA, Carlos Gaston',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (312,4,'FERRARA, Carlos Gaston',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (313,1,'FERNANDEZ, Leandro Carlos',2,2017,89);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (314,2,'SCARAMUZZA, Carlos Jose',2,2017,89);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (315,1,'SCARAMUZZA, Carlos Jose',2,2017,95);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (316,2,'SCARAMUZZA, Carlos Jose',2,2017,95);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (317,1,'A DESIGNAR',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (318,2,'BALDINO, Emiliano',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (319,3,'BALDINO, Emiliano',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (320,4,'BALDINO, Emiliano',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (321,1,'DE RONDE, Chirstian',2,2017,70);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (322,2,'PAGOLA, Bernardo',2,2017,62);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (323,3,'PAGOLA, Bernardo',2,2017,62);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (324,4,'SOTO, Roberto Eduardo',2,2017,62);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (325,5,'FONTAN, Alejandro',2,2017,62);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (326,1,'OSIO, Jorge Rafael',2,2017,63);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (327,1,'OSIO, Jorge Rafael',2,2017,63);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (328,2,'MONTEZANTI, Diego Miguel',2,2017,63);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (329,2,'MONTEZANTI, Diego Miguel',2,2017,63);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (330,3,'MONTEZANTI, Diego Miguel',2,2017,63);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (331,3,'MONTEZANTI, Diego Miguel',2,2017,63);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (332,4,'SALVATORE, Juan Eduardo',2,2017,63);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (333,4,'SALVATORE, Juan Eduardo',2,2017,63);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (334,1,'SZYMANOWSKI, Alicia Noemi',2,2017,64);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (335,2,'GALARZA, BRIAN IVAN',2,2017,64);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (336,3,'GALARZA, BRIAN IVAN',2,2017,64);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (337,4,'GROSS, Patricio Martín',2,2017,64);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (338,5,'ATIA, María Julissa',2,2017,64);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (339,5,'ATIA, María Julissa',2,2017,64);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (340,1,'IULIANO, Pablo José',2,2017,67);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (341,1,'IULIANO, Pablo José',2,2017,67);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (342,2,'AMET, Leonardo Javier',2,2017,67);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (343,3,'SUAREZ, Matías Gabriel',2,2017,67);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (344,3,'SUAREZ, Matías Gabriel',2,2017,67);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (345,4,'GUZMAN, Jesica Vanesa',2,2017,67);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (346,1,'BERMUDEZ CICCHINO, Andrea Noelia',2,2017,69);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (347,2,'GROSS, Patricio Martín',2,2017,69);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (348,1,'VAELLO, Augusto Martín',2,2017,68);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (349,2,'VAELLO, Augusto Martín',2,2017,68);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (350,3,'SABATINO, Pablo Luis Esteban',2,2017,68);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (351,3,'SABATINO, Pablo Luis Esteban',2,2017,68);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (352,4,'SABATINO, Pablo Luis Esteban',2,2017,68);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (353,4,'SABATINO, Pablo Luis Esteban',2,2017,68);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (354,1,'HASPERUE, Waldo',2,2017,71);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (355,2,'GONZALEZ CASCO, Pablo Andres',2,2017,71);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (356,3,'PAGOLA, Bernardo',2,2017,71);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (357,1,'GROSS, Patricio Martín',2,2017,72);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (358,2,'COLANERO, Nicolás Sebastían',2,2017,72);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (359,1,'CONDE, Sergio Daniel',2,2017,73);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (360,1,'IRIARTE, Leandro',2,2017,74);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (361,1,'CORTES BRACHO, Oscar Leonardo',2,2017,76);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (362,2,'CORTES BRACHO, Oscar Leonardo',2,2017,76);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (363,2,'CORTES BRACHO, Oscar Leonardo',2,2017,76);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (364,2,'CORTES BRACHO, Oscar Leonardo',2,2017,76);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (365,1,'CAPPELLETTI, Claudia Marcela',2,2017,78);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (366,1,'CAPPELLETTI, Claudia Marcela',2,2017,78);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (367,1,'BUENAMELIS, EMANUEL CARLOS EMILI',2,2017,79);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (368,2,NULL,2,2017,79);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (369,1,'GRISPINO, Marcelo Fabián',2,2017,80);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (370,1,'GRISPINO, Marcelo Fabián',2,2017,80);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (371,1,'ALONSO, Carlos Daniel',2,2017,82);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (372,1,'ALONSO, Carlos Daniel',2,2017,82);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (373,2,'SALVATORE, Juan Eduardo',2,2017,82);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (374,1,'SCHENONE, Carlos Alberto',2,2017,83);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (375,1,'SUAREZ, Matías Gabriel',2,2017,84);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (376,1,'SUAREZ, Matías Gabriel',2,2017,84);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (377,1,'ANTONINI, Sergio Andres',2,2017,85);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (378,1,'OSIO, Jorge Rafael',2,2017,86);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (379,1,'OSIO, Jorge Rafael',2,2017,86);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (380,1,'OSIO, Jorge Rafael',2,2017,86);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (381,1,'ENCINAS, Diego Omar',2,2017,87);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (382,1,'ENCINAS, Diego Omar',2,2017,87);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (383,1,'KUNYSZ, Eduardo',2,2017,103);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (384,1,'NAPOLITANO, Sergio Alejandro',2,2017,100);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (385,1,'GONZALEZ, Sebastián Martin',2,2017,99);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (386,1,'GONZALEZ, Sebastián Martin',2,2017,99);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (387,1,'VAZQUEZ, Alejandro David',2,2017,101);
INSERT INTO `comision` (`idcomision`,`numero`,`profesor`,`cuatrimestre`,`year`,`materia_idmateria`) VALUES (388,1,'MORALES, Daniel Martin',2,2017,97);
