<?php

namespace AppBundle\Repository;

/**
 * CalendarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarioRepository extends \Doctrine\ORM\EntityRepository
{
}
