<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Comision extends \AppBundle\Entity\Comision implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'numero', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'profesor', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'cuatrimestre', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'year', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'idcomision', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'materiamateria'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'numero', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'profesor', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'cuatrimestre', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'year', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'idcomision', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'materiamateria'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Comision $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesor($profesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesor', [$profesor]);

        return parent::setProfesor($profesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesor', []);

        return parent::getProfesor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuatrimestre($cuatrimestre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuatrimestre', [$cuatrimestre]);

        return parent::setCuatrimestre($cuatrimestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuatrimestre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuatrimestre', []);

        return parent::getCuatrimestre();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear($year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', [$year]);

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', []);

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcomision()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcomision();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcomision', []);

        return parent::getIdcomision();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriamateria(\AppBundle\Entity\Materia $materiamateria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriamateria', [$materiamateria]);

        return parent::setMateriamateria($materiamateria);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriamateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriamateria', []);

        return parent::getMateriamateria();
    }

}
